_homepage:
    pattern: /
    defaults: { _controller: MyLoremBundle:Default:index }

my_dolor:
    resource: "@MyDolorBundle/Controller/"
    type:     annotation
    prefix:   /

my_ipsum:
    resource: "@MyIpsumBundle/Controller/"
    type:     annotation
    prefix:   /

my_lorem:
    resource: "@MyLoremBundle/Controller/"
    type:     annotation
    prefix:   /



my_zabytek:
    resource: "@MyZabytekBundle/Controller/"
    type:     annotation
    prefix:   /



my_fraszka:
    resource: "@MyFraszkaBundle/Controller/"
    type:     annotation
    prefix:   /



my_poem:
    resource: "@MyPoemBundle/Controller/"
    type:     annotation
    prefix:   /



my_lake:
    resource: "@MyLakeBundle/Controller/"
    type:     annotation
    prefix:   /



my_valley:
    resource: "@MyValleyBundle/Controller/"
    type:     annotation
    prefix:   /
    defaults: { _controller: MyValleyBundle:Default:index }

my_helloworld:
    resource: "@MyHelloworldBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

