_homepage:
    pattern: /
    defaults: { _controller: MyKoloryBundle:Default:index }

my_kolory:
    resource: "@MyKoloryBundle/Controller/"
    type:     annotation
    prefix:   /



my_mnozenie:
    resource: "@MyMnozenieBundle/Controller/"
    type:     annotation
    prefix:   /


my_tabliczka:
    resource: "@MyTabliczkaBundle/Controller/"
    type:     annotation
    prefix:   /



my_korona:
    resource: "@MyKoronaBundle/Controller/"
    type:     annotation
    prefix:   /


my_mount:
    resource: "@MyMountBundle/Controller/"
    type:     annotation
    prefix:   /





my_valley:
    resource: "@MyValleyBundle/Controller/"
    type:     annotation
    prefix:   /

my_mountains:
    resource: "@MyMountainsBundle/Controller/"
    type:     annotation
    prefix:   /
#    defaults: { _controller: MyMountainsBundle:Default:index }

#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation
